package com.qudiandu.smartreader.service.db.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qudiandu.smartreader.ui.task.model.bean.SRTaskListenHistory;
import com.qudiandu.smartreader.ui.dubbing.model.bean.SRMarkBean;
import com.qudiandu.smartreader.ui.set.model.bean.SRSysMsg;
import com.qudiandu.smartreader.ui.main.model.bean.SRBook;
import com.qudiandu.smartreader.ui.login.model.bean.SRUser;

import com.qudiandu.smartreader.service.db.entity.SRTaskListenHistoryDao;
import com.qudiandu.smartreader.service.db.entity.SRMarkBeanDao;
import com.qudiandu.smartreader.service.db.entity.SRSysMsgDao;
import com.qudiandu.smartreader.service.db.entity.SRBookDao;
import com.qudiandu.smartreader.service.db.entity.SRUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sRTaskListenHistoryDaoConfig;
    private final DaoConfig sRMarkBeanDaoConfig;
    private final DaoConfig sRSysMsgDaoConfig;
    private final DaoConfig sRBookDaoConfig;
    private final DaoConfig sRUserDaoConfig;

    private final SRTaskListenHistoryDao sRTaskListenHistoryDao;
    private final SRMarkBeanDao sRMarkBeanDao;
    private final SRSysMsgDao sRSysMsgDao;
    private final SRBookDao sRBookDao;
    private final SRUserDao sRUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sRTaskListenHistoryDaoConfig = daoConfigMap.get(SRTaskListenHistoryDao.class).clone();
        sRTaskListenHistoryDaoConfig.initIdentityScope(type);

        sRMarkBeanDaoConfig = daoConfigMap.get(SRMarkBeanDao.class).clone();
        sRMarkBeanDaoConfig.initIdentityScope(type);

        sRSysMsgDaoConfig = daoConfigMap.get(SRSysMsgDao.class).clone();
        sRSysMsgDaoConfig.initIdentityScope(type);

        sRBookDaoConfig = daoConfigMap.get(SRBookDao.class).clone();
        sRBookDaoConfig.initIdentityScope(type);

        sRUserDaoConfig = daoConfigMap.get(SRUserDao.class).clone();
        sRUserDaoConfig.initIdentityScope(type);

        sRTaskListenHistoryDao = new SRTaskListenHistoryDao(sRTaskListenHistoryDaoConfig, this);
        sRMarkBeanDao = new SRMarkBeanDao(sRMarkBeanDaoConfig, this);
        sRSysMsgDao = new SRSysMsgDao(sRSysMsgDaoConfig, this);
        sRBookDao = new SRBookDao(sRBookDaoConfig, this);
        sRUserDao = new SRUserDao(sRUserDaoConfig, this);

        registerDao(SRTaskListenHistory.class, sRTaskListenHistoryDao);
        registerDao(SRMarkBean.class, sRMarkBeanDao);
        registerDao(SRSysMsg.class, sRSysMsgDao);
        registerDao(SRBook.class, sRBookDao);
        registerDao(SRUser.class, sRUserDao);
    }
    
    public void clear() {
        sRTaskListenHistoryDaoConfig.clearIdentityScope();
        sRMarkBeanDaoConfig.clearIdentityScope();
        sRSysMsgDaoConfig.clearIdentityScope();
        sRBookDaoConfig.clearIdentityScope();
        sRUserDaoConfig.clearIdentityScope();
    }

    public SRTaskListenHistoryDao getSRTaskListenHistoryDao() {
        return sRTaskListenHistoryDao;
    }

    public SRMarkBeanDao getSRMarkBeanDao() {
        return sRMarkBeanDao;
    }

    public SRSysMsgDao getSRSysMsgDao() {
        return sRSysMsgDao;
    }

    public SRBookDao getSRBookDao() {
        return sRBookDao;
    }

    public SRUserDao getSRUserDao() {
        return sRUserDao;
    }

}
