package com.smartreader.service.db.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.smartreader.ui.main.model.bean.SRBook;

import com.smartreader.service.db.entity.SRBookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sRBookDaoConfig;

    private final SRBookDao sRBookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sRBookDaoConfig = daoConfigMap.get(SRBookDao.class).clone();
        sRBookDaoConfig.initIdentityScope(type);

        sRBookDao = new SRBookDao(sRBookDaoConfig, this);

        registerDao(SRBook.class, sRBookDao);
    }
    
    public void clear() {
        sRBookDaoConfig.clearIdentityScope();
    }

    public SRBookDao getSRBookDao() {
        return sRBookDao;
    }

}
